DATASET:
  FOLDS_COUNT: 5
  MEAN: 0.1307
  PATH: mnist
  STD: 0.3081
  TOTAL_CLASS_COUNT: 10
  PERCENTAGES: [10, 20, 30, 40, 50]
MODEL:
  LATENT_SIZE: 16
  Z_DISCRIMINATOR_CROSS_BATCH: False
  INPUT_IMAGE_SIZE: 32
  INPUT_IMAGE_CHANNELS: 1
OUTPUT_DIR: results
TRAIN:
  BASE_LEARNING_RATE: 0.002
  BATCH_SIZE: 128
  EPOCH_COUNT: 80

OUTPUT_FOLDER: 'results'
RESULTS_NAME: 'results_mnist.csv'

LOSSES: 'classic'
