from .train import train_model
from .test import test_model
from .usnet import train_usnet_model
from .fn3 import train_fn3_model
from .l1 import train_l1_model
from .lr import train_lr_model
from .nestdnn import train_nestdnn_model
from .kd_lit import train_kd_lit
from .ofa import train_ofa_resnet18_cifar100_model
from .nestdnnv3 import train_nestdnnv3_model